// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.minh.grpc_service.user;

public interface GetUserInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.GetUserInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();
}
