// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.minh.grpc_service.user;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_GetUserInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_GetUserInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_GetUserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_GetUserInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\032net.devh.boot.grpc.example" +
      "\"\'\n\022GetUserInfoRequest\022\021\n\taccountId\030\001 \001(" +
      "\t\"\206\001\n\023GetUserInfoResponse\022\016\n\006status\030\001 \001(" +
      "\005\022\017\n\007message\030\002 \001(\t\022\021\n\taccountId\030\003 \001(\t\022\020\n" +
      "\010username\030\004 \001(\t\022\020\n\010fullName\030\005 \001(\t\022\027\n\017shi" +
      "ppingAddress\030\006 \001(\t2}\n\013UserService\022n\n\013Get" +
      "UserInfo\022..net.devh.boot.grpc.example.Ge" +
      "tUserInfoRequest\032/.net.devh.boot.grpc.ex" +
      "ample.GetUserInfoResponseB)\n\032com.minh.gr" +
      "pc_service.userB\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_devh_boot_grpc_example_GetUserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_devh_boot_grpc_example_GetUserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_GetUserInfoRequest_descriptor,
        new java.lang.String[] { "AccountId", });
    internal_static_net_devh_boot_grpc_example_GetUserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_devh_boot_grpc_example_GetUserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_GetUserInfoResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "AccountId", "Username", "FullName", "ShippingAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
