spring:
  threads:
    virtual:
      enabled: true
  application:
    name: auth-service
  datasource:
    url: "jdbc:h2:file:~/data/auth;AUTO_SERVER=true"
    driver-class-name: "org.h2.Driver"
    username: sa
    password: ''
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true