spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    stream:
      binders:
        kafka:
          default-candidate: true
      kafka:
        binder:
          brokers:
            - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
    config:
      server:
        git:
          uri: https://github.com/MaivMinh/e-commerce-config
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: MaivMinh
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # Liveness and Readiness probes configuration.
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071