// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc_service.product;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantByIdRequest}
 */
public final class FindProductVariantByIdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.FindProductVariantByIdRequest)
    FindProductVariantByIdRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindProductVariantByIdRequest.newBuilder() to construct.
  private FindProductVariantByIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindProductVariantByIdRequest() {
    productVariantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindProductVariantByIdRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc_service.product.FindProductVariantByIdRequest.class, com.minh.grpc_service.product.FindProductVariantByIdRequest.Builder.class);
  }

  public static final int PRODUCT_VARIANT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object productVariantId_;
  /**
   * <code>string product_variant_id = 1;</code>
   * @return The productVariantId.
   */
  @java.lang.Override
  public java.lang.String getProductVariantId() {
    java.lang.Object ref = productVariantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productVariantId_ = s;
      return s;
    }
  }
  /**
   * <code>string product_variant_id = 1;</code>
   * @return The bytes for productVariantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductVariantIdBytes() {
    java.lang.Object ref = productVariantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productVariantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productVariantId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productVariantId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc_service.product.FindProductVariantByIdRequest)) {
      return super.equals(obj);
    }
    com.minh.grpc_service.product.FindProductVariantByIdRequest other = (com.minh.grpc_service.product.FindProductVariantByIdRequest) obj;

    if (!getProductVariantId()
        .equals(other.getProductVariantId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCT_VARIANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductVariantId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantByIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc_service.product.FindProductVariantByIdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantByIdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.FindProductVariantByIdRequest)
      com.minh.grpc_service.product.FindProductVariantByIdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc_service.product.FindProductVariantByIdRequest.class, com.minh.grpc_service.product.FindProductVariantByIdRequest.Builder.class);
    }

    // Construct using com.minh.grpc_service.product.FindProductVariantByIdRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productVariantId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantByIdRequest getDefaultInstanceForType() {
      return com.minh.grpc_service.product.FindProductVariantByIdRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantByIdRequest build() {
      com.minh.grpc_service.product.FindProductVariantByIdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantByIdRequest buildPartial() {
      com.minh.grpc_service.product.FindProductVariantByIdRequest result = new com.minh.grpc_service.product.FindProductVariantByIdRequest(this);
      result.productVariantId_ = productVariantId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc_service.product.FindProductVariantByIdRequest) {
        return mergeFrom((com.minh.grpc_service.product.FindProductVariantByIdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc_service.product.FindProductVariantByIdRequest other) {
      if (other == com.minh.grpc_service.product.FindProductVariantByIdRequest.getDefaultInstance()) return this;
      if (!other.getProductVariantId().isEmpty()) {
        productVariantId_ = other.productVariantId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              productVariantId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object productVariantId_ = "";
    /**
     * <code>string product_variant_id = 1;</code>
     * @return The productVariantId.
     */
    public java.lang.String getProductVariantId() {
      java.lang.Object ref = productVariantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productVariantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_variant_id = 1;</code>
     * @return The bytes for productVariantId.
     */
    public com.google.protobuf.ByteString
        getProductVariantIdBytes() {
      java.lang.Object ref = productVariantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVariantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_variant_id = 1;</code>
     * @param value The productVariantId to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productVariantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_variant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantId() {
      
      productVariantId_ = getDefaultInstance().getProductVariantId();
      onChanged();
      return this;
    }
    /**
     * <code>string product_variant_id = 1;</code>
     * @param value The bytes for productVariantId to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productVariantId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.FindProductVariantByIdRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.FindProductVariantByIdRequest)
  private static final com.minh.grpc_service.product.FindProductVariantByIdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc_service.product.FindProductVariantByIdRequest();
  }

  public static com.minh.grpc_service.product.FindProductVariantByIdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindProductVariantByIdRequest>
      PARSER = new com.google.protobuf.AbstractParser<FindProductVariantByIdRequest>() {
    @java.lang.Override
    public FindProductVariantByIdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FindProductVariantByIdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindProductVariantByIdRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc_service.product.FindProductVariantByIdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

