// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc_service.product;

public interface FindProductVariantByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_variant_id = 1;</code>
   * @return The productVariantId.
   */
  java.lang.String getProductVariantId();
  /**
   * <code>string product_variant_id = 1;</code>
   * @return The bytes for productVariantId.
   */
  com.google.protobuf.ByteString
      getProductVariantIdBytes();
}
