// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc_service.product;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantsByIdsRequest}
 */
public final class FindProductVariantsByIdsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
    FindProductVariantsByIdsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindProductVariantsByIdsRequest.newBuilder() to construct.
  private FindProductVariantsByIdsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindProductVariantsByIdsRequest() {
    cartItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindProductVariantsByIdsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc_service.product.FindProductVariantsByIdsRequest.class, com.minh.grpc_service.product.FindProductVariantsByIdsRequest.Builder.class);
  }

  public static final int CARTITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc> cartItems_;
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc> getCartItemsList() {
    return cartItems_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder> 
      getCartItemsOrBuilderList() {
    return cartItems_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  @java.lang.Override
  public int getCartItemsCount() {
    return cartItems_.size();
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  @java.lang.Override
  public com.minh.grpc_service.product.CartItemMessageGrpc getCartItems(int index) {
    return cartItems_.get(index);
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  @java.lang.Override
  public com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder getCartItemsOrBuilder(
      int index) {
    return cartItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cartItems_.size(); i++) {
      output.writeMessage(1, cartItems_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cartItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cartItems_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc_service.product.FindProductVariantsByIdsRequest)) {
      return super.equals(obj);
    }
    com.minh.grpc_service.product.FindProductVariantsByIdsRequest other = (com.minh.grpc_service.product.FindProductVariantsByIdsRequest) obj;

    if (!getCartItemsList()
        .equals(other.getCartItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCartItemsCount() > 0) {
      hash = (37 * hash) + CARTITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getCartItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc_service.product.FindProductVariantsByIdsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantsByIdsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
      com.minh.grpc_service.product.FindProductVariantsByIdsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc_service.product.FindProductVariantsByIdsRequest.class, com.minh.grpc_service.product.FindProductVariantsByIdsRequest.Builder.class);
    }

    // Construct using com.minh.grpc_service.product.FindProductVariantsByIdsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
      } else {
        cartItems_ = null;
        cartItemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc_service.product.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantsByIdsRequest getDefaultInstanceForType() {
      return com.minh.grpc_service.product.FindProductVariantsByIdsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantsByIdsRequest build() {
      com.minh.grpc_service.product.FindProductVariantsByIdsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc_service.product.FindProductVariantsByIdsRequest buildPartial() {
      com.minh.grpc_service.product.FindProductVariantsByIdsRequest result = new com.minh.grpc_service.product.FindProductVariantsByIdsRequest(this);
      int from_bitField0_ = bitField0_;
      if (cartItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cartItems_ = java.util.Collections.unmodifiableList(cartItems_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cartItems_ = cartItems_;
      } else {
        result.cartItems_ = cartItemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc_service.product.FindProductVariantsByIdsRequest) {
        return mergeFrom((com.minh.grpc_service.product.FindProductVariantsByIdsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc_service.product.FindProductVariantsByIdsRequest other) {
      if (other == com.minh.grpc_service.product.FindProductVariantsByIdsRequest.getDefaultInstance()) return this;
      if (cartItemsBuilder_ == null) {
        if (!other.cartItems_.isEmpty()) {
          if (cartItems_.isEmpty()) {
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCartItemsIsMutable();
            cartItems_.addAll(other.cartItems_);
          }
          onChanged();
        }
      } else {
        if (!other.cartItems_.isEmpty()) {
          if (cartItemsBuilder_.isEmpty()) {
            cartItemsBuilder_.dispose();
            cartItemsBuilder_ = null;
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cartItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCartItemsFieldBuilder() : null;
          } else {
            cartItemsBuilder_.addAllMessages(other.cartItems_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.minh.grpc_service.product.CartItemMessageGrpc m =
                  input.readMessage(
                      com.minh.grpc_service.product.CartItemMessageGrpc.parser(),
                      extensionRegistry);
              if (cartItemsBuilder_ == null) {
                ensureCartItemsIsMutable();
                cartItems_.add(m);
              } else {
                cartItemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc> cartItems_ =
      java.util.Collections.emptyList();
    private void ensureCartItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cartItems_ = new java.util.ArrayList<com.minh.grpc_service.product.CartItemMessageGrpc>(cartItems_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minh.grpc_service.product.CartItemMessageGrpc, com.minh.grpc_service.product.CartItemMessageGrpc.Builder, com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder> cartItemsBuilder_;

    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc> getCartItemsList() {
      if (cartItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cartItems_);
      } else {
        return cartItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public int getCartItemsCount() {
      if (cartItemsBuilder_ == null) {
        return cartItems_.size();
      } else {
        return cartItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public com.minh.grpc_service.product.CartItemMessageGrpc getCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);
      } else {
        return cartItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder setCartItems(
        int index, com.minh.grpc_service.product.CartItemMessageGrpc value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.set(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder setCartItems(
        int index, com.minh.grpc_service.product.CartItemMessageGrpc.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder addCartItems(com.minh.grpc_service.product.CartItemMessageGrpc value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder addCartItems(
        int index, com.minh.grpc_service.product.CartItemMessageGrpc value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder addCartItems(
        com.minh.grpc_service.product.CartItemMessageGrpc.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder addCartItems(
        int index, com.minh.grpc_service.product.CartItemMessageGrpc.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder addAllCartItems(
        java.lang.Iterable<? extends com.minh.grpc_service.product.CartItemMessageGrpc> values) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cartItems_);
        onChanged();
      } else {
        cartItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder clearCartItems() {
      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cartItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public Builder removeCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.remove(index);
        onChanged();
      } else {
        cartItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public com.minh.grpc_service.product.CartItemMessageGrpc.Builder getCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder getCartItemsOrBuilder(
        int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);  } else {
        return cartItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public java.util.List<? extends com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder> 
         getCartItemsOrBuilderList() {
      if (cartItemsBuilder_ != null) {
        return cartItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cartItems_);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public com.minh.grpc_service.product.CartItemMessageGrpc.Builder addCartItemsBuilder() {
      return getCartItemsFieldBuilder().addBuilder(
          com.minh.grpc_service.product.CartItemMessageGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public com.minh.grpc_service.product.CartItemMessageGrpc.Builder addCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().addBuilder(
          index, com.minh.grpc_service.product.CartItemMessageGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
     */
    public java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc.Builder> 
         getCartItemsBuilderList() {
      return getCartItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minh.grpc_service.product.CartItemMessageGrpc, com.minh.grpc_service.product.CartItemMessageGrpc.Builder, com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder> 
        getCartItemsFieldBuilder() {
      if (cartItemsBuilder_ == null) {
        cartItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.minh.grpc_service.product.CartItemMessageGrpc, com.minh.grpc_service.product.CartItemMessageGrpc.Builder, com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder>(
                cartItems_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cartItems_ = null;
      }
      return cartItemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
  private static final com.minh.grpc_service.product.FindProductVariantsByIdsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc_service.product.FindProductVariantsByIdsRequest();
  }

  public static com.minh.grpc_service.product.FindProductVariantsByIdsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindProductVariantsByIdsRequest>
      PARSER = new com.google.protobuf.AbstractParser<FindProductVariantsByIdsRequest>() {
    @java.lang.Override
    public FindProductVariantsByIdsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FindProductVariantsByIdsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindProductVariantsByIdsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc_service.product.FindProductVariantsByIdsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

