// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc_service.product;

public interface FindProductVariantsByIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  java.util.List<com.minh.grpc_service.product.CartItemMessageGrpc> 
      getCartItemsList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  com.minh.grpc_service.product.CartItemMessageGrpc getCartItems(int index);
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  java.util.List<? extends com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemMessageGrpc cartItems = 1;</code>
   */
  com.minh.grpc_service.product.CartItemMessageGrpcOrBuilder getCartItemsOrBuilder(
      int index);
}
