// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc_service.product;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_CartItemMessageGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_CartItemMessageGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_ProductVariantMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\032net.devh.boot.grpc.exam" +
      "ple\";\n\035FindProductVariantByIdRequest\022\032\n\022" +
      "product_variant_id\030\001 \001(\t\"\240\001\n\016ProductVari" +
      "ant\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004slug\030\003 " +
      "\001(\t\022\014\n\004size\030\004 \001(\t\022\021\n\tcolorName\030\005 \001(\t\022\020\n\010" +
      "colorHex\030\006 \001(\t\022\r\n\005cover\030\007 \001(\t\022\r\n\005price\030\010" +
      " \001(\001\022\025\n\roriginalPrice\030\t \001(\001\"\205\001\n\036FindProd" +
      "uctVariantByIdResponse\022\016\n\006status\030\001 \001(\005\022\017" +
      "\n\007message\030\002 \001(\t\022B\n\016productVariant\030\003 \001(\0132" +
      "*.net.devh.boot.grpc.example.ProductVari" +
      "ant\"C\n\023CartItemMessageGrpc\022\022\n\ncartItemId" +
      "\030\001 \001(\t\022\030\n\020productVariantId\030\002 \001(\t\"\244\002\n\025Pro" +
      "ductVariantMessage\022\022\n\ncartItemId\030\001 \001(\t\022\030" +
      "\n\020productVariantId\030\002 \001(\t\022\023\n\013productName\030" +
      "\003 \001(\t\022\023\n\013productSlug\030\004 \001(\t\022\032\n\022productVar" +
      "iantSize\030\005 \001(\t\022\037\n\027productVariantColorNam" +
      "e\030\006 \001(\t\022\036\n\026productVariantColorHex\030\007 \001(\t\022" +
      "\024\n\014productCover\030\010 \001(\t\022\033\n\023productVariantP" +
      "rice\030\t \001(\001\022#\n\033productVariantOriginalPric" +
      "e\030\n \001(\001\"e\n\037FindProductVariantsByIdsReque" +
      "st\022B\n\tcartItems\030\001 \003(\0132/.net.devh.boot.gr" +
      "pc.example.CartItemMessageGrpc\"\217\001\n FindP" +
      "roductVariantsByIdsResponse\022\016\n\006status\030\001 " +
      "\001(\005\022\017\n\007message\030\002 \001(\t\022J\n\017productVariants\030" +
      "\003 \003(\01321.net.devh.boot.grpc.example.Produ" +
      "ctVariantMessage2\272\002\n\016ProductService\022\217\001\n\026" +
      "FindProductVariantById\0229.net.devh.boot.g" +
      "rpc.example.FindProductVariantByIdReques" +
      "t\032:.net.devh.boot.grpc.example.FindProdu" +
      "ctVariantByIdResponse\022\225\001\n\030FindProductVar" +
      "iantsByIds\022;.net.devh.boot.grpc.example." +
      "FindProductVariantsByIdsRequest\032<.net.de" +
      "vh.boot.grpc.example.FindProductVariants" +
      "ByIdsResponseB/\n\035com.minh.grpc_service.p" +
      "roductB\014ProductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor,
        new java.lang.String[] { "ProductVariantId", });
    internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor,
        new java.lang.String[] { "Id", "Name", "Slug", "Size", "ColorName", "ColorHex", "Cover", "Price", "OriginalPrice", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "ProductVariant", });
    internal_static_net_devh_boot_grpc_example_CartItemMessageGrpc_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_net_devh_boot_grpc_example_CartItemMessageGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_CartItemMessageGrpc_descriptor,
        new java.lang.String[] { "CartItemId", "ProductVariantId", });
    internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_net_devh_boot_grpc_example_ProductVariantMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor,
        new java.lang.String[] { "CartItemId", "ProductVariantId", "ProductName", "ProductSlug", "ProductVariantSize", "ProductVariantColorName", "ProductVariantColorHex", "ProductCover", "ProductVariantPrice", "ProductVariantOriginalPrice", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor,
        new java.lang.String[] { "CartItems", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "ProductVariants", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
