// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.minh.grpc_service.auth;

public interface AuthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.AuthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates if the authentication was successful
   * </pre>
   *
   * <code>bool isValid = 1;</code>
   * @return The isValid.
   */
  boolean getIsValid();

  /**
   * <pre>
   * A message providing additional information about the authentication result
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * A message providing additional information about the authentication result
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   * @return Whether the authInfo field is set.
   */
  boolean hasAuthInfo();
  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   * @return The authInfo.
   */
  com.minh.grpc_service.auth.AuthInfo getAuthInfo();
  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   */
  com.minh.grpc_service.auth.AuthInfoOrBuilder getAuthInfoOrBuilder();
}
