// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.minh.grpc_service.auth;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_AuthInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_AuthInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_AuthResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\032net.devh.boot.grpc.example" +
      "\"\034\n\013AuthRequest\022\r\n\005token\030\001 \001(\t\",\n\010AuthIn" +
      "fo\022\022\n\naccount_id\030\001 \001(\t\022\014\n\004role\030\002 \001(\t\"x\n\014" +
      "AuthResponse\022\017\n\007isValid\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t\022\016\n\006status\030\003 \001(\005\0226\n\010authInfo\030\004 \001(\013" +
      "2$.net.devh.boot.grpc.example.AuthInfo2p" +
      "\n\013AuthService\022a\n\014Authenticate\022\'.net.devh" +
      ".boot.grpc.example.AuthRequest\032(.net.dev" +
      "h.boot.grpc.example.AuthResponseB)\n\032com." +
      "minh.grpc_service.authB\tAuthProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_devh_boot_grpc_example_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_devh_boot_grpc_example_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_AuthRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_net_devh_boot_grpc_example_AuthInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_devh_boot_grpc_example_AuthInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_AuthInfo_descriptor,
        new java.lang.String[] { "AccountId", "Role", });
    internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_devh_boot_grpc_example_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor,
        new java.lang.String[] { "IsValid", "Message", "Status", "AuthInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
