// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.minh.grpc_service.auth;

public interface AuthInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.AuthInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the account being authenticated
   * </pre>
   *
   * <code>string account_id = 1;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <pre>
   * The ID of the account being authenticated
   * </pre>
   *
   * <code>string account_id = 1;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <pre>
   * The role of the user (e.g., admin, user)
   * </pre>
   *
   * <code>string role = 2;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <pre>
   * The role of the user (e.g., admin, user)
   * </pre>
   *
   * <code>string role = 2;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
