// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.minh.grpc_service.auth;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.AuthResponse}
 */
public final class AuthResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.AuthResponse)
    AuthResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthResponse.newBuilder() to construct.
  private AuthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthResponse() {
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc_service.auth.AuthProto.internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc_service.auth.AuthProto.internal_static_net_devh_boot_grpc_example_AuthResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc_service.auth.AuthResponse.class, com.minh.grpc_service.auth.AuthResponse.Builder.class);
  }

  public static final int ISVALID_FIELD_NUMBER = 1;
  private boolean isValid_;
  /**
   * <pre>
   * Indicates if the authentication was successful
   * </pre>
   *
   * <code>bool isValid = 1;</code>
   * @return The isValid.
   */
  @java.lang.Override
  public boolean getIsValid() {
    return isValid_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * A message providing additional information about the authentication result
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A message providing additional information about the authentication result
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHINFO_FIELD_NUMBER = 3;
  private com.minh.grpc_service.auth.AuthInfo authInfo_;
  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   * @return Whether the authInfo field is set.
   */
  @java.lang.Override
  public boolean hasAuthInfo() {
    return authInfo_ != null;
  }
  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   * @return The authInfo.
   */
  @java.lang.Override
  public com.minh.grpc_service.auth.AuthInfo getAuthInfo() {
    return authInfo_ == null ? com.minh.grpc_service.auth.AuthInfo.getDefaultInstance() : authInfo_;
  }
  /**
   * <pre>
   * Additional information about the authenticated user
   * </pre>
   *
   * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
   */
  @java.lang.Override
  public com.minh.grpc_service.auth.AuthInfoOrBuilder getAuthInfoOrBuilder() {
    return getAuthInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isValid_ != false) {
      output.writeBool(1, isValid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (authInfo_ != null) {
      output.writeMessage(3, getAuthInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isValid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isValid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (authInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAuthInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc_service.auth.AuthResponse)) {
      return super.equals(obj);
    }
    com.minh.grpc_service.auth.AuthResponse other = (com.minh.grpc_service.auth.AuthResponse) obj;

    if (getIsValid()
        != other.getIsValid()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasAuthInfo() != other.hasAuthInfo()) return false;
    if (hasAuthInfo()) {
      if (!getAuthInfo()
          .equals(other.getAuthInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISVALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsValid());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasAuthInfo()) {
      hash = (37 * hash) + AUTHINFO_FIELD_NUMBER;
      hash = (53 * hash) + getAuthInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc_service.auth.AuthResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc_service.auth.AuthResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.AuthResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.AuthResponse)
      com.minh.grpc_service.auth.AuthResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc_service.auth.AuthProto.internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc_service.auth.AuthProto.internal_static_net_devh_boot_grpc_example_AuthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc_service.auth.AuthResponse.class, com.minh.grpc_service.auth.AuthResponse.Builder.class);
    }

    // Construct using com.minh.grpc_service.auth.AuthResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isValid_ = false;

      message_ = "";

      if (authInfoBuilder_ == null) {
        authInfo_ = null;
      } else {
        authInfo_ = null;
        authInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc_service.auth.AuthProto.internal_static_net_devh_boot_grpc_example_AuthResponse_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc_service.auth.AuthResponse getDefaultInstanceForType() {
      return com.minh.grpc_service.auth.AuthResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc_service.auth.AuthResponse build() {
      com.minh.grpc_service.auth.AuthResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc_service.auth.AuthResponse buildPartial() {
      com.minh.grpc_service.auth.AuthResponse result = new com.minh.grpc_service.auth.AuthResponse(this);
      result.isValid_ = isValid_;
      result.message_ = message_;
      if (authInfoBuilder_ == null) {
        result.authInfo_ = authInfo_;
      } else {
        result.authInfo_ = authInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc_service.auth.AuthResponse) {
        return mergeFrom((com.minh.grpc_service.auth.AuthResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc_service.auth.AuthResponse other) {
      if (other == com.minh.grpc_service.auth.AuthResponse.getDefaultInstance()) return this;
      if (other.getIsValid() != false) {
        setIsValid(other.getIsValid());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasAuthInfo()) {
        mergeAuthInfo(other.getAuthInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isValid_ = input.readBool();

              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAuthInfoFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private boolean isValid_ ;
    /**
     * <pre>
     * Indicates if the authentication was successful
     * </pre>
     *
     * <code>bool isValid = 1;</code>
     * @return The isValid.
     */
    @java.lang.Override
    public boolean getIsValid() {
      return isValid_;
    }
    /**
     * <pre>
     * Indicates if the authentication was successful
     * </pre>
     *
     * <code>bool isValid = 1;</code>
     * @param value The isValid to set.
     * @return This builder for chaining.
     */
    public Builder setIsValid(boolean value) {
      
      isValid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the authentication was successful
     * </pre>
     *
     * <code>bool isValid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsValid() {
      
      isValid_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * A message providing additional information about the authentication result
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A message providing additional information about the authentication result
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A message providing additional information about the authentication result
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message providing additional information about the authentication result
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message providing additional information about the authentication result
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.minh.grpc_service.auth.AuthInfo authInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minh.grpc_service.auth.AuthInfo, com.minh.grpc_service.auth.AuthInfo.Builder, com.minh.grpc_service.auth.AuthInfoOrBuilder> authInfoBuilder_;
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     * @return Whether the authInfo field is set.
     */
    public boolean hasAuthInfo() {
      return authInfoBuilder_ != null || authInfo_ != null;
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     * @return The authInfo.
     */
    public com.minh.grpc_service.auth.AuthInfo getAuthInfo() {
      if (authInfoBuilder_ == null) {
        return authInfo_ == null ? com.minh.grpc_service.auth.AuthInfo.getDefaultInstance() : authInfo_;
      } else {
        return authInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public Builder setAuthInfo(com.minh.grpc_service.auth.AuthInfo value) {
      if (authInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authInfo_ = value;
        onChanged();
      } else {
        authInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public Builder setAuthInfo(
        com.minh.grpc_service.auth.AuthInfo.Builder builderForValue) {
      if (authInfoBuilder_ == null) {
        authInfo_ = builderForValue.build();
        onChanged();
      } else {
        authInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public Builder mergeAuthInfo(com.minh.grpc_service.auth.AuthInfo value) {
      if (authInfoBuilder_ == null) {
        if (authInfo_ != null) {
          authInfo_ =
            com.minh.grpc_service.auth.AuthInfo.newBuilder(authInfo_).mergeFrom(value).buildPartial();
        } else {
          authInfo_ = value;
        }
        onChanged();
      } else {
        authInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public Builder clearAuthInfo() {
      if (authInfoBuilder_ == null) {
        authInfo_ = null;
        onChanged();
      } else {
        authInfo_ = null;
        authInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public com.minh.grpc_service.auth.AuthInfo.Builder getAuthInfoBuilder() {
      
      onChanged();
      return getAuthInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    public com.minh.grpc_service.auth.AuthInfoOrBuilder getAuthInfoOrBuilder() {
      if (authInfoBuilder_ != null) {
        return authInfoBuilder_.getMessageOrBuilder();
      } else {
        return authInfo_ == null ?
            com.minh.grpc_service.auth.AuthInfo.getDefaultInstance() : authInfo_;
      }
    }
    /**
     * <pre>
     * Additional information about the authenticated user
     * </pre>
     *
     * <code>.net.devh.boot.grpc.example.AuthInfo authInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minh.grpc_service.auth.AuthInfo, com.minh.grpc_service.auth.AuthInfo.Builder, com.minh.grpc_service.auth.AuthInfoOrBuilder> 
        getAuthInfoFieldBuilder() {
      if (authInfoBuilder_ == null) {
        authInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minh.grpc_service.auth.AuthInfo, com.minh.grpc_service.auth.AuthInfo.Builder, com.minh.grpc_service.auth.AuthInfoOrBuilder>(
                getAuthInfo(),
                getParentForChildren(),
                isClean());
        authInfo_ = null;
      }
      return authInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.AuthResponse)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.AuthResponse)
  private static final com.minh.grpc_service.auth.AuthResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc_service.auth.AuthResponse();
  }

  public static com.minh.grpc_service.auth.AuthResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthResponse>() {
    @java.lang.Override
    public AuthResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc_service.auth.AuthResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

