// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.product_service_grpc;

public interface ProductVariantMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.ProductVariantMessageDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cartItemId = 1;</code>
   * @return The cartItemId.
   */
  java.lang.String getCartItemId();
  /**
   * <code>string cartItemId = 1;</code>
   * @return The bytes for cartItemId.
   */
  com.google.protobuf.ByteString
      getCartItemIdBytes();

  /**
   * <code>string productVariantId = 2;</code>
   * @return The productVariantId.
   */
  java.lang.String getProductVariantId();
  /**
   * <code>string productVariantId = 2;</code>
   * @return The bytes for productVariantId.
   */
  com.google.protobuf.ByteString
      getProductVariantIdBytes();

  /**
   * <code>string productName = 3;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 3;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productSlug = 4;</code>
   * @return The productSlug.
   */
  java.lang.String getProductSlug();
  /**
   * <code>string productSlug = 4;</code>
   * @return The bytes for productSlug.
   */
  com.google.protobuf.ByteString
      getProductSlugBytes();

  /**
   * <code>string productVariantSize = 5;</code>
   * @return The productVariantSize.
   */
  java.lang.String getProductVariantSize();
  /**
   * <code>string productVariantSize = 5;</code>
   * @return The bytes for productVariantSize.
   */
  com.google.protobuf.ByteString
      getProductVariantSizeBytes();

  /**
   * <code>string productVariantColorName = 6;</code>
   * @return The productVariantColorName.
   */
  java.lang.String getProductVariantColorName();
  /**
   * <code>string productVariantColorName = 6;</code>
   * @return The bytes for productVariantColorName.
   */
  com.google.protobuf.ByteString
      getProductVariantColorNameBytes();

  /**
   * <code>string productVariantColorHex = 7;</code>
   * @return The productVariantColorHex.
   */
  java.lang.String getProductVariantColorHex();
  /**
   * <code>string productVariantColorHex = 7;</code>
   * @return The bytes for productVariantColorHex.
   */
  com.google.protobuf.ByteString
      getProductVariantColorHexBytes();

  /**
   * <code>string productCover = 8;</code>
   * @return The productCover.
   */
  java.lang.String getProductCover();
  /**
   * <code>string productCover = 8;</code>
   * @return The bytes for productCover.
   */
  com.google.protobuf.ByteString
      getProductCoverBytes();

  /**
   * <code>double productVariantPrice = 9;</code>
   * @return The productVariantPrice.
   */
  double getProductVariantPrice();

  /**
   * <code>double productVariantOriginalPrice = 10;</code>
   * @return The productVariantOriginalPrice.
   */
  double getProductVariantOriginalPrice();
}
