// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.product_service_grpc;

public interface FindProductVariantsByIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantsByIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariantMessage productVariants = 3;</code>
   */
  java.util.List<com.minh.product_service_grpc.ProductVariantMessage> 
      getProductVariantsList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariantMessage productVariants = 3;</code>
   */
  com.minh.product_service_grpc.ProductVariantMessage getProductVariants(int index);
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariantMessage productVariants = 3;</code>
   */
  int getProductVariantsCount();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariantMessage productVariants = 3;</code>
   */
  java.util.List<? extends com.minh.product_service_grpc.ProductVariantMessageOrBuilder> 
      getProductVariantsOrBuilderList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariantMessage productVariants = 3;</code>
   */
  com.minh.product_service_grpc.ProductVariantMessageOrBuilder getProductVariantsOrBuilder(
      int index);
}
