// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.product_service_grpc;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.ProductVariantMessage}
 */
public final class ProductVariantMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.ProductVariantMessage)
    ProductVariantMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductVariantMessage.newBuilder() to construct.
  private ProductVariantMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductVariantMessage() {
    cartItemId_ = "";
    productVariantId_ = "";
    productName_ = "";
    productSlug_ = "";
    productVariantSize_ = "";
    productVariantColorName_ = "";
    productVariantColorHex_ = "";
    productCover_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductVariantMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.product_service_grpc.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.product_service_grpc.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariantMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.product_service_grpc.ProductVariantMessage.class, com.minh.product_service_grpc.ProductVariantMessage.Builder.class);
  }

  public static final int CARTITEMID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cartItemId_;
  /**
   * <code>string cartItemId = 1;</code>
   * @return The cartItemId.
   */
  @java.lang.Override
  public java.lang.String getCartItemId() {
    java.lang.Object ref = cartItemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cartItemId_ = s;
      return s;
    }
  }
  /**
   * <code>string cartItemId = 1;</code>
   * @return The bytes for cartItemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCartItemIdBytes() {
    java.lang.Object ref = cartItemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cartItemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object productVariantId_;
  /**
   * <code>string productVariantId = 2;</code>
   * @return The productVariantId.
   */
  @java.lang.Override
  public java.lang.String getProductVariantId() {
    java.lang.Object ref = productVariantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productVariantId_ = s;
      return s;
    }
  }
  /**
   * <code>string productVariantId = 2;</code>
   * @return The bytes for productVariantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductVariantIdBytes() {
    java.lang.Object ref = productVariantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productVariantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object productName_;
  /**
   * <code>string productName = 3;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string productName = 3;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTSLUG_FIELD_NUMBER = 4;
  private volatile java.lang.Object productSlug_;
  /**
   * <code>string productSlug = 4;</code>
   * @return The productSlug.
   */
  @java.lang.Override
  public java.lang.String getProductSlug() {
    java.lang.Object ref = productSlug_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productSlug_ = s;
      return s;
    }
  }
  /**
   * <code>string productSlug = 4;</code>
   * @return The bytes for productSlug.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductSlugBytes() {
    java.lang.Object ref = productSlug_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productSlug_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANTSIZE_FIELD_NUMBER = 5;
  private volatile java.lang.Object productVariantSize_;
  /**
   * <code>string productVariantSize = 5;</code>
   * @return The productVariantSize.
   */
  @java.lang.Override
  public java.lang.String getProductVariantSize() {
    java.lang.Object ref = productVariantSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productVariantSize_ = s;
      return s;
    }
  }
  /**
   * <code>string productVariantSize = 5;</code>
   * @return The bytes for productVariantSize.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductVariantSizeBytes() {
    java.lang.Object ref = productVariantSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productVariantSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANTCOLORNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object productVariantColorName_;
  /**
   * <code>string productVariantColorName = 6;</code>
   * @return The productVariantColorName.
   */
  @java.lang.Override
  public java.lang.String getProductVariantColorName() {
    java.lang.Object ref = productVariantColorName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productVariantColorName_ = s;
      return s;
    }
  }
  /**
   * <code>string productVariantColorName = 6;</code>
   * @return The bytes for productVariantColorName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductVariantColorNameBytes() {
    java.lang.Object ref = productVariantColorName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productVariantColorName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANTCOLORHEX_FIELD_NUMBER = 7;
  private volatile java.lang.Object productVariantColorHex_;
  /**
   * <code>string productVariantColorHex = 7;</code>
   * @return The productVariantColorHex.
   */
  @java.lang.Override
  public java.lang.String getProductVariantColorHex() {
    java.lang.Object ref = productVariantColorHex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productVariantColorHex_ = s;
      return s;
    }
  }
  /**
   * <code>string productVariantColorHex = 7;</code>
   * @return The bytes for productVariantColorHex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductVariantColorHexBytes() {
    java.lang.Object ref = productVariantColorHex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productVariantColorHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTCOVER_FIELD_NUMBER = 8;
  private volatile java.lang.Object productCover_;
  /**
   * <code>string productCover = 8;</code>
   * @return The productCover.
   */
  @java.lang.Override
  public java.lang.String getProductCover() {
    java.lang.Object ref = productCover_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productCover_ = s;
      return s;
    }
  }
  /**
   * <code>string productCover = 8;</code>
   * @return The bytes for productCover.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductCoverBytes() {
    java.lang.Object ref = productCover_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productCover_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANTPRICE_FIELD_NUMBER = 9;
  private double productVariantPrice_;
  /**
   * <code>double productVariantPrice = 9;</code>
   * @return The productVariantPrice.
   */
  @java.lang.Override
  public double getProductVariantPrice() {
    return productVariantPrice_;
  }

  public static final int PRODUCTVARIANTORIGINALPRICE_FIELD_NUMBER = 10;
  private double productVariantOriginalPrice_;
  /**
   * <code>double productVariantOriginalPrice = 10;</code>
   * @return The productVariantOriginalPrice.
   */
  @java.lang.Override
  public double getProductVariantOriginalPrice() {
    return productVariantOriginalPrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cartItemId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cartItemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productVariantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productSlug_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productSlug_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantSize_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productVariantSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantColorName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, productVariantColorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantColorHex_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, productVariantColorHex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCover_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, productCover_);
    }
    if (java.lang.Double.doubleToRawLongBits(productVariantPrice_) != 0) {
      output.writeDouble(9, productVariantPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(productVariantOriginalPrice_) != 0) {
      output.writeDouble(10, productVariantOriginalPrice_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cartItemId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cartItemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productVariantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productSlug_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productSlug_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantSize_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productVariantSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantColorName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, productVariantColorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productVariantColorHex_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, productVariantColorHex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCover_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, productCover_);
    }
    if (java.lang.Double.doubleToRawLongBits(productVariantPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, productVariantPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(productVariantOriginalPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, productVariantOriginalPrice_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.product_service_grpc.ProductVariantMessage)) {
      return super.equals(obj);
    }
    com.minh.product_service_grpc.ProductVariantMessage other = (com.minh.product_service_grpc.ProductVariantMessage) obj;

    if (!getCartItemId()
        .equals(other.getCartItemId())) return false;
    if (!getProductVariantId()
        .equals(other.getProductVariantId())) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (!getProductSlug()
        .equals(other.getProductSlug())) return false;
    if (!getProductVariantSize()
        .equals(other.getProductVariantSize())) return false;
    if (!getProductVariantColorName()
        .equals(other.getProductVariantColorName())) return false;
    if (!getProductVariantColorHex()
        .equals(other.getProductVariantColorHex())) return false;
    if (!getProductCover()
        .equals(other.getProductCover())) return false;
    if (java.lang.Double.doubleToLongBits(getProductVariantPrice())
        != java.lang.Double.doubleToLongBits(
            other.getProductVariantPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getProductVariantOriginalPrice())
        != java.lang.Double.doubleToLongBits(
            other.getProductVariantOriginalPrice())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARTITEMID_FIELD_NUMBER;
    hash = (53 * hash) + getCartItemId().hashCode();
    hash = (37 * hash) + PRODUCTVARIANTID_FIELD_NUMBER;
    hash = (53 * hash) + getProductVariantId().hashCode();
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + PRODUCTSLUG_FIELD_NUMBER;
    hash = (53 * hash) + getProductSlug().hashCode();
    hash = (37 * hash) + PRODUCTVARIANTSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getProductVariantSize().hashCode();
    hash = (37 * hash) + PRODUCTVARIANTCOLORNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductVariantColorName().hashCode();
    hash = (37 * hash) + PRODUCTVARIANTCOLORHEX_FIELD_NUMBER;
    hash = (53 * hash) + getProductVariantColorHex().hashCode();
    hash = (37 * hash) + PRODUCTCOVER_FIELD_NUMBER;
    hash = (53 * hash) + getProductCover().hashCode();
    hash = (37 * hash) + PRODUCTVARIANTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getProductVariantPrice()));
    hash = (37 * hash) + PRODUCTVARIANTORIGINALPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getProductVariantOriginalPrice()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.product_service_grpc.ProductVariantMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.product_service_grpc.ProductVariantMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.ProductVariantMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.ProductVariantMessage)
      com.minh.product_service_grpc.ProductVariantMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.product_service_grpc.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.product_service_grpc.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariantMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.product_service_grpc.ProductVariantMessage.class, com.minh.product_service_grpc.ProductVariantMessage.Builder.class);
    }

    // Construct using com.minh.product_service_grpc.ProductVariantMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cartItemId_ = "";

      productVariantId_ = "";

      productName_ = "";

      productSlug_ = "";

      productVariantSize_ = "";

      productVariantColorName_ = "";

      productVariantColorHex_ = "";

      productCover_ = "";

      productVariantPrice_ = 0D;

      productVariantOriginalPrice_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.product_service_grpc.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariantMessage_descriptor;
    }

    @java.lang.Override
    public com.minh.product_service_grpc.ProductVariantMessage getDefaultInstanceForType() {
      return com.minh.product_service_grpc.ProductVariantMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.product_service_grpc.ProductVariantMessage build() {
      com.minh.product_service_grpc.ProductVariantMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.product_service_grpc.ProductVariantMessage buildPartial() {
      com.minh.product_service_grpc.ProductVariantMessage result = new com.minh.product_service_grpc.ProductVariantMessage(this);
      result.cartItemId_ = cartItemId_;
      result.productVariantId_ = productVariantId_;
      result.productName_ = productName_;
      result.productSlug_ = productSlug_;
      result.productVariantSize_ = productVariantSize_;
      result.productVariantColorName_ = productVariantColorName_;
      result.productVariantColorHex_ = productVariantColorHex_;
      result.productCover_ = productCover_;
      result.productVariantPrice_ = productVariantPrice_;
      result.productVariantOriginalPrice_ = productVariantOriginalPrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.product_service_grpc.ProductVariantMessage) {
        return mergeFrom((com.minh.product_service_grpc.ProductVariantMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.product_service_grpc.ProductVariantMessage other) {
      if (other == com.minh.product_service_grpc.ProductVariantMessage.getDefaultInstance()) return this;
      if (!other.getCartItemId().isEmpty()) {
        cartItemId_ = other.cartItemId_;
        onChanged();
      }
      if (!other.getProductVariantId().isEmpty()) {
        productVariantId_ = other.productVariantId_;
        onChanged();
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        onChanged();
      }
      if (!other.getProductSlug().isEmpty()) {
        productSlug_ = other.productSlug_;
        onChanged();
      }
      if (!other.getProductVariantSize().isEmpty()) {
        productVariantSize_ = other.productVariantSize_;
        onChanged();
      }
      if (!other.getProductVariantColorName().isEmpty()) {
        productVariantColorName_ = other.productVariantColorName_;
        onChanged();
      }
      if (!other.getProductVariantColorHex().isEmpty()) {
        productVariantColorHex_ = other.productVariantColorHex_;
        onChanged();
      }
      if (!other.getProductCover().isEmpty()) {
        productCover_ = other.productCover_;
        onChanged();
      }
      if (other.getProductVariantPrice() != 0D) {
        setProductVariantPrice(other.getProductVariantPrice());
      }
      if (other.getProductVariantOriginalPrice() != 0D) {
        setProductVariantOriginalPrice(other.getProductVariantOriginalPrice());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cartItemId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              productVariantId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              productName_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              productSlug_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              productVariantSize_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              productVariantColorName_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              productVariantColorHex_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              productCover_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 73: {
              productVariantPrice_ = input.readDouble();

              break;
            } // case 73
            case 81: {
              productVariantOriginalPrice_ = input.readDouble();

              break;
            } // case 81
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object cartItemId_ = "";
    /**
     * <code>string cartItemId = 1;</code>
     * @return The cartItemId.
     */
    public java.lang.String getCartItemId() {
      java.lang.Object ref = cartItemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cartItemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cartItemId = 1;</code>
     * @return The bytes for cartItemId.
     */
    public com.google.protobuf.ByteString
        getCartItemIdBytes() {
      java.lang.Object ref = cartItemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cartItemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cartItemId = 1;</code>
     * @param value The cartItemId to set.
     * @return This builder for chaining.
     */
    public Builder setCartItemId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartItemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cartItemId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCartItemId() {
      
      cartItemId_ = getDefaultInstance().getCartItemId();
      onChanged();
      return this;
    }
    /**
     * <code>string cartItemId = 1;</code>
     * @param value The bytes for cartItemId to set.
     * @return This builder for chaining.
     */
    public Builder setCartItemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartItemId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productVariantId_ = "";
    /**
     * <code>string productVariantId = 2;</code>
     * @return The productVariantId.
     */
    public java.lang.String getProductVariantId() {
      java.lang.Object ref = productVariantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productVariantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productVariantId = 2;</code>
     * @return The bytes for productVariantId.
     */
    public com.google.protobuf.ByteString
        getProductVariantIdBytes() {
      java.lang.Object ref = productVariantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVariantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productVariantId = 2;</code>
     * @param value The productVariantId to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productVariantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantId() {
      
      productVariantId_ = getDefaultInstance().getProductVariantId();
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantId = 2;</code>
     * @param value The bytes for productVariantId to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productVariantId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string productName = 3;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productName = 3;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productName = 3;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      
      productName_ = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 3;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productSlug_ = "";
    /**
     * <code>string productSlug = 4;</code>
     * @return The productSlug.
     */
    public java.lang.String getProductSlug() {
      java.lang.Object ref = productSlug_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productSlug_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productSlug = 4;</code>
     * @return The bytes for productSlug.
     */
    public com.google.protobuf.ByteString
        getProductSlugBytes() {
      java.lang.Object ref = productSlug_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productSlug_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productSlug = 4;</code>
     * @param value The productSlug to set.
     * @return This builder for chaining.
     */
    public Builder setProductSlug(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productSlug_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productSlug = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductSlug() {
      
      productSlug_ = getDefaultInstance().getProductSlug();
      onChanged();
      return this;
    }
    /**
     * <code>string productSlug = 4;</code>
     * @param value The bytes for productSlug to set.
     * @return This builder for chaining.
     */
    public Builder setProductSlugBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productSlug_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productVariantSize_ = "";
    /**
     * <code>string productVariantSize = 5;</code>
     * @return The productVariantSize.
     */
    public java.lang.String getProductVariantSize() {
      java.lang.Object ref = productVariantSize_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productVariantSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productVariantSize = 5;</code>
     * @return The bytes for productVariantSize.
     */
    public com.google.protobuf.ByteString
        getProductVariantSizeBytes() {
      java.lang.Object ref = productVariantSize_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVariantSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productVariantSize = 5;</code>
     * @param value The productVariantSize to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productVariantSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantSize = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantSize() {
      
      productVariantSize_ = getDefaultInstance().getProductVariantSize();
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantSize = 5;</code>
     * @param value The bytes for productVariantSize to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productVariantSize_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productVariantColorName_ = "";
    /**
     * <code>string productVariantColorName = 6;</code>
     * @return The productVariantColorName.
     */
    public java.lang.String getProductVariantColorName() {
      java.lang.Object ref = productVariantColorName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productVariantColorName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productVariantColorName = 6;</code>
     * @return The bytes for productVariantColorName.
     */
    public com.google.protobuf.ByteString
        getProductVariantColorNameBytes() {
      java.lang.Object ref = productVariantColorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVariantColorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productVariantColorName = 6;</code>
     * @param value The productVariantColorName to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantColorName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productVariantColorName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantColorName = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantColorName() {
      
      productVariantColorName_ = getDefaultInstance().getProductVariantColorName();
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantColorName = 6;</code>
     * @param value The bytes for productVariantColorName to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantColorNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productVariantColorName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productVariantColorHex_ = "";
    /**
     * <code>string productVariantColorHex = 7;</code>
     * @return The productVariantColorHex.
     */
    public java.lang.String getProductVariantColorHex() {
      java.lang.Object ref = productVariantColorHex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productVariantColorHex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productVariantColorHex = 7;</code>
     * @return The bytes for productVariantColorHex.
     */
    public com.google.protobuf.ByteString
        getProductVariantColorHexBytes() {
      java.lang.Object ref = productVariantColorHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVariantColorHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productVariantColorHex = 7;</code>
     * @param value The productVariantColorHex to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantColorHex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productVariantColorHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantColorHex = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantColorHex() {
      
      productVariantColorHex_ = getDefaultInstance().getProductVariantColorHex();
      onChanged();
      return this;
    }
    /**
     * <code>string productVariantColorHex = 7;</code>
     * @param value The bytes for productVariantColorHex to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantColorHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productVariantColorHex_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productCover_ = "";
    /**
     * <code>string productCover = 8;</code>
     * @return The productCover.
     */
    public java.lang.String getProductCover() {
      java.lang.Object ref = productCover_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCover_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productCover = 8;</code>
     * @return The bytes for productCover.
     */
    public com.google.protobuf.ByteString
        getProductCoverBytes() {
      java.lang.Object ref = productCover_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCover_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productCover = 8;</code>
     * @param value The productCover to set.
     * @return This builder for chaining.
     */
    public Builder setProductCover(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productCover_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productCover = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductCover() {
      
      productCover_ = getDefaultInstance().getProductCover();
      onChanged();
      return this;
    }
    /**
     * <code>string productCover = 8;</code>
     * @param value The bytes for productCover to set.
     * @return This builder for chaining.
     */
    public Builder setProductCoverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productCover_ = value;
      onChanged();
      return this;
    }

    private double productVariantPrice_ ;
    /**
     * <code>double productVariantPrice = 9;</code>
     * @return The productVariantPrice.
     */
    @java.lang.Override
    public double getProductVariantPrice() {
      return productVariantPrice_;
    }
    /**
     * <code>double productVariantPrice = 9;</code>
     * @param value The productVariantPrice to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantPrice(double value) {
      
      productVariantPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double productVariantPrice = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantPrice() {
      
      productVariantPrice_ = 0D;
      onChanged();
      return this;
    }

    private double productVariantOriginalPrice_ ;
    /**
     * <code>double productVariantOriginalPrice = 10;</code>
     * @return The productVariantOriginalPrice.
     */
    @java.lang.Override
    public double getProductVariantOriginalPrice() {
      return productVariantOriginalPrice_;
    }
    /**
     * <code>double productVariantOriginalPrice = 10;</code>
     * @param value The productVariantOriginalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setProductVariantOriginalPrice(double value) {
      
      productVariantOriginalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double productVariantOriginalPrice = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductVariantOriginalPrice() {
      
      productVariantOriginalPrice_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.ProductVariantMessage)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.ProductVariantMessage)
  private static final com.minh.product_service_grpc.ProductVariantMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.product_service_grpc.ProductVariantMessage();
  }

  public static com.minh.product_service_grpc.ProductVariantMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductVariantMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProductVariantMessage>() {
    @java.lang.Override
    public ProductVariantMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductVariantMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductVariantMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.product_service_grpc.ProductVariantMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

