services:

  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - e-commerce
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M

  axon-server:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - e-commerce
    volumes:
      - "/root/data/axonserver/data:/axonserver/data"
      - "/root/data/axonserver/events:/axonserver/events"
      - "/root/data/axonserver/config:/axonserver/config"
    restart: unless-stopped


  kafka:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092:9092"
    networks:
      - e-commerce
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT


  config-server:
    image: config-server:1.0
    restart: on-failure
    networks:
      - e-commerce
    ports:
      - "8071:8071"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 400M
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092

  service-discovery:
    image: service-discovery:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=service-discovery
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 400M

  redis-service:
    image: redis:7.4
    restart: unless-stopped
    networks:
      - e-commerce
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 400M
  api-gateway:
    image: api-gateway:1.0
    restart: on-failure
    networks:
      - e-commerce
    deploy:
      resources:
        limits:
          memory: 400M
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis-service
      - SPRING_DATA_REDIS_PORT=6379
      - GRPC_SERVER_AUTH_SERVICE_ADDRESS=static://auth-service:9093
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans

  db-service:
    image: mysql:8.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=ecommerce_auth
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - /root/data/ecommerce-db:/var/lib/mysql

  # =======================
  # Authentication Service
  # =======================
  auth-service:
    image: auth-service:1.0
    networks:
      - e-commerce
    deploy:
      resources:
        limits:
          memory: 512M
    restart: on-failure
    env_file:
      - .env
    ports:
      - "9093:9093"
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - SPRING_APPLICATION_SECURITY_JWT_ACCESS_TOKEN_KEY=${SPRING_APPLICATION_SECURITY_JWT_ACCESS_TOKEN_KEY}
      - SPRING_APPLICATION_SECURITY_JWT_REFRESH_TOKEN_KEY=${SPRING_APPLICATION_SECURITY_JWT_REFRESH_TOKEN_KEY}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis-service
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      - SPRING_SQL_INIT_MODE=never
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_auth
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans

  # =======================
  # Cart Service
  # =======================
  cart-service:
    image: cart-service:1.0
    networks:
      - e-commerce
    deploy:
      resources:
        limits:
          memory: 512M
    restart: on-failure
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=cart-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_CLOUDFRONT_DOMAIN=${AWS_CLOUDFRONT_DOMAIN}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_cart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - GRPC_SERVER_PRODUCT_SERVICE_ADDRESS=static://product-service:9091
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans

  # =======================
  # Order Service
  # =======================
  order-service:
    image: order-service:1.0
    networks:
      - e-commerce
    deploy:
      resources:
        limits:
          memory: 768M
    restart: on-failure
    ports:
      - "9094:9094"
      - "8084:8084"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=order-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_order
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - GRPC_SERVER_USER_SERVICE_ADDRESS=static://user-service:9098
      - GRPC_SERVER_PRODUCT_SERVICE_ADDRESS=static://product-service:9091
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans

  # =======================
  # Payment Service
  # =======================
  payment-service:
    deploy:
      resources:
        limits:
          memory: 512M
    image: payment-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=payment-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_payment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans



  # =======================
  # Product Service
  # =======================

  product-service:
    deploy:
      resources:
        limits:
          memory: 768M
    image: product-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "9091:9091"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_product
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans



  # =======================
  # Promotion Service
  # =======================
  promotion-service:
    deploy:
      resources:
        limits:
          memory: 512M
    image: promotion-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=promotion-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_promotion
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans


  # =======================
  # User Service
  # =======================
  user-service:
    deploy:
      resources:
        limits:
          memory: 400M
    image: user-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8088:8088"
      - "9098:9098"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans


  # =======================
  # File Service
  # =======================
  file-service:
    deploy:
      resources:
        limits:
          memory: 400M
    image: file-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=file-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans


  # =======================
  # Review Service
  # =======================
  review-service:
    deploy:
      resources:
        limits:
          memory: 512M
    image: review-service:1.0
    restart: on-failure
    networks:
      - e-commerce
    env_file:
      - .env
    ports:
      - "8087:8087"
    environment:
      - SPRING_APPLICATION_NAME=review-service
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/ecommerce_review
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans


networks:
  e-commerce:
    driver: "bridge"

# =======================
# Docker Volumes
# =======================d
volumes:
  db-service:
    driver: local
  kafka_data:
    driver: local